### ISSUE TITLE
Use of dynamic Classes instead of hard-coded ones

### ISSUE THREAD

**Issue by domi-btnr** [KingGamingYT/discord-no-mosaic#1]
Hello,

You use hard-coded Classes like `.wrapperControlsHidden_f72aac` which could break functionality of some features. Try to update them to dynamic classes like `[class*=wrapperControlsHidden_]`

Also use `BdApi.DOM.addStyle` and `BdApi.DOM.removeStyle` instead of `document.body.appendChild` and `document.body.removeChild`

**Comment by KingGamingYT** [comment]
Your second point should be fixed in 42f4c6b, however, changing hard-coded classes to dynamic (or wildcard) ones inside styles leads to some pretty bad sluggishness in areas such as the video UI.

**Comment by Yentis** [comment]
Classes can also be retrieved using getModule, for example:
![Discord_hqspPrCnvZ](https://github.com/user-attachments/assets/0e1daa0e-9993-4552-8f28-5e24837c9bfb)

**Comment by domi-btnr** [comment]
I think I might have had a bit of a miscommunication with Zere. I wasn’t sure how classes that are hard-coded into plugins are handled, so I asked for some advice. Zere said that as long as the whole plugin doesn’t break if the classes change, it’s not a big deal, but he would recommend using dynamic classes. When they don't update frequently then I think it should be fine using hard-coded ones.

If you want to go with the Webpack route, then you could use something like this:
```js
const styles = Object.assign(
    BdApi.Webpack.getByKeys("visualMediaItemContainer"),
    BdApi.Webpack.getByKeys("wrapperControlsHidden")
);

const css = `
${styles.visualMediaItemContainer}, ${styles.imageWrapper}:has(>a) {
    max-width: 400px !important;
}
`;
 ```

But yeah, sorry for the inconvenience. Totally my fault

**Comment by KingGamingYT** [comment]
All good! I always appreciate the feedback.

**Comment by KingGamingYT** [comment]
classes are no longer hard-coded, done by andy in e453f8c (ignore the bdfdb shit it was removed next commit because andy forgot)
